// 种子数据源文件
import { Status, WeekDay, AttendanceStatus } from '@csisp/types';

// 姓氏数组
export const FIRST_NAMES = [
  '张',
  '王',
  '李',
  '赵',
  '刘',
  '陈',
  '杨',
  '黄',
  '周',
  '吴',
  '徐',
  '孙',
  '胡',
  '朱',
  '高',
  '林',
  '何',
  '郭',
  '马',
  '罗',
  '梁',
  '宋',
  '郑',
  '谢',
  '韩',
  '唐',
  '冯',
  '于',
  '董',
  '萧',
];

// 名字数组
export const MIDDLE_NAMES = [
  '伟',
  '芳',
  '娜',
  '秀英',
  '敏',
  '静',
  '强',
  '磊',
  '军',
  '洋',
  '勇',
  '艳',
  '杰',
  '娟',
  '涛',
  '明',
  '超',
  '秀兰',
  '霞',
  '平',
  '刚',
  '桂',
  '芳',
  '英',
  '琴',
  '华',
  '丹',
  '梅',
  '雪',
  '敏',
];

// 男生名字
export const MALE_NAMES = [
  '伟',
  '强',
  '磊',
  '军',
  '洋',
  '勇',
  '杰',
  '涛',
  '明',
  '超',
  '刚',
  '健',
  '辉',
  '军',
  '强',
  '飞',
  '鹏',
  '龙',
  '伟',
  '杰',
];

// 女生名字
export const FEMALE_NAMES = [
  '芳',
  '娜',
  '秀英',
  '敏',
  '静',
  '艳',
  '娟',
  '秀兰',
  '霞',
  '平',
  '桂',
  '芳',
  '英',
  '琴',
  '华',
  '丹',
  '梅',
  '雪',
  '敏',
  '丽',
];

// 专业列表
export const MAJORS = ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'];

// 课程数据数组
// 课程数据类型定义
export interface CourseDataItem {
  name: string;
  code: string;
  semester: string;
  academicYear: number;
  description: string;
  credit: number;
  availableMajors: string[];
  status: Status;
}

// 教师数据类型定义
export interface TeacherDataItem {
  realName: string;
  email: string;
  phone: string;
  department: string;
  userId?: number | null;
  status: Status;
}

export const COURSE_DATA: CourseDataItem[] = [
  {
    name: '高等数学A(1)',
    code: 'MA101',
    semester: '2025-1',
    academicYear: 2025,
    description: '高等数学基础课程',
    credit: 5,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '程序设计基础',
    code: 'CS101',
    semester: '2025-1',
    academicYear: 2025,
    description: '计算机编程入门课程',
    credit: 4,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '大学英语(1)',
    code: 'EN101',
    semester: '2025-1',
    academicYear: 2025,
    description: '大学英语基础课程',
    credit: 4,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '思想道德修养与法律基础',
    code: 'P101',
    semester: '2025-1',
    academicYear: 2025,
    description: '思想政治教育课程',
    credit: 3,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '体育(1)',
    code: 'PE101',
    semester: '2025-1',
    academicYear: 2025,
    description: '体育基础课程',
    credit: 2,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '高等数学A(2)',
    code: 'MA102',
    semester: '2025-2',
    academicYear: 2025,
    description: '高等数学进阶课程',
    credit: 5,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '数据结构',
    code: 'CS102',
    semester: '2025-2',
    academicYear: 2025,
    description: '数据结构与算法课程',
    credit: 4,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '大学英语(2)',
    code: 'EN102',
    semester: '2025-2',
    academicYear: 2025,
    description: '大学英语进阶课程',
    credit: 4,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '中国近现代史纲要',
    code: 'H101',
    semester: '2025-2',
    academicYear: 2025,
    description: '中国近现代历史课程',
    credit: 2,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '体育(2)',
    code: 'PE102',
    semester: '2025-2',
    academicYear: 2025,
    description: '体育进阶课程',
    credit: 2,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '高等数学B(1)',
    code: 'MA103',
    semester: '2025-3',
    academicYear: 2025,
    description: '高等数学应用课程',
    credit: 4,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '计算机组成原理',
    code: 'CS201',
    semester: '2025-3',
    academicYear: 2025,
    description: '计算机硬件基础课程',
    credit: 4,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '离散数学',
    code: 'MA201',
    semester: '2025-3',
    academicYear: 2025,
    description: '离散数学理论课程',
    credit: 3,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '大学英语(3)',
    code: 'EN103',
    semester: '2025-3',
    academicYear: 2025,
    description: '大学英语高级课程',
    credit: 4,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '马克思主义基本原理',
    code: 'M101',
    semester: '2025-3',
    academicYear: 2025,
    description: '马克思主义理论课程',
    credit: 3,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '高等数学B(2)',
    code: 'MA104',
    semester: '2025-4',
    academicYear: 2025,
    description: '高等数学高级应用课程',
    credit: 4,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '操作系统',
    code: 'CS202',
    semester: '2025-4',
    academicYear: 2025,
    description: '操作系统原理与实现',
    credit: 4,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '数据库系统原理',
    code: 'CS203',
    semester: '2025-4',
    academicYear: 2025,
    description: '数据库设计与实现课程',
    credit: 4,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '大学英语(4)',
    code: 'EN104',
    semester: '2025-4',
    academicYear: 2025,
    description: '专业英语课程',
    credit: 4,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '毛泽东思想和中国特色社会主义理论体系概论',
    code: 'M102',
    semester: '2025-4',
    academicYear: 2025,
    description: '中国特色社会主义理论课程',
    credit: 3,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '计算机网络',
    code: 'CS301',
    semester: '2025-5',
    academicYear: 2025,
    description: '计算机网络原理与技术',
    credit: 4,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '软件工程',
    code: 'CS302',
    semester: '2025-5',
    academicYear: 2025,
    description: '软件工程方法与实践',
    credit: 4,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）'],
    status: Status.Active,
  },
  {
    name: '网络安全',
    code: 'CS303',
    semester: '2025-5',
    academicYear: 2025,
    description: '网络安全原理与技术',
    credit: 4,
    availableMajors: ['计算机科学与技术', '网络工程'],
    status: Status.Active,
  },
  {
    name: '数字逻辑',
    code: 'EE201',
    semester: '2025-5',
    academicYear: 2025,
    description: '数字电路与逻辑设计',
    credit: 3,
    availableMajors: ['计算机科学与技术', '网络工程'],
    status: Status.Active,
  },
  {
    name: '人工智能导论',
    code: 'CS304',
    semester: '2025-5',
    academicYear: 2025,
    description: '人工智能基础理论与应用',
    credit: 4,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）'],
    status: Status.Active,
  },
  {
    name: '编译原理',
    code: 'CS305',
    semester: '2025-6',
    academicYear: 2025,
    description: '编译器设计原理与实现',
    credit: 4,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）'],
    status: Status.Active,
  },
  {
    name: 'Web前端开发',
    code: 'CS306',
    semester: '2025-6',
    academicYear: 2025,
    description: '现代Web前端技术',
    credit: 4,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）', '网络工程'],
    status: Status.Active,
  },
  {
    name: '云计算技术',
    code: 'CS307',
    semester: '2025-6',
    academicYear: 2025,
    description: '云计算原理与实践',
    credit: 4,
    availableMajors: ['计算机科学与技术', '网络工程'],
    status: Status.Active,
  },
  {
    name: '计算机图形学',
    code: 'CS308',
    semester: '2025-6',
    academicYear: 2025,
    description: '计算机图形学原理与应用',
    credit: 3,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）'],
    status: Status.Active,
  },
  {
    name: '数据分析',
    code: 'CS309',
    semester: '2025-6',
    academicYear: 2025,
    description: '大数据分析方法与技术',
    credit: 4,
    availableMajors: ['计算机科学与技术', '计算机科学与技术（师范）'],
    status: Status.Active,
  },
];

// 教师数据数组
export const TEACHERS: TeacherDataItem[] = [
  {
    realName: '张教授',
    email: 'zhang@cs.edu.cn',
    phone: '13800138011',
    department: '计算机科学与技术系',
    status: Status.Active,
  },
  {
    realName: '李教授',
    email: 'li@cs.edu.cn',
    phone: '13800138012',
    department: '计算机科学与技术系',
    status: Status.Active,
  },
  {
    realName: '王教授',
    email: 'wang@cs.edu.cn',
    phone: '13800138013',
    department: '计算机科学与技术系',
    status: Status.Active,
  },
  {
    realName: '刘教授',
    email: 'liu@cs.edu.cn',
    phone: '13800138014',
    department: '计算机科学与技术系',
    status: Status.Active,
  },
  {
    realName: '陈教授',
    email: 'chen@cs.edu.cn',
    phone: '13800138015',
    department: '计算机科学与技术系',
    status: Status.Active,
  },
  {
    realName: '赵教授',
    email: 'zhao@cs.edu.cn',
    phone: '13800138016',
    department: '网络工程系',
    status: Status.Active,
  },
  {
    realName: '钱教授',
    email: 'qian@cs.edu.cn',
    phone: '13800138017',
    department: '网络工程系',
    status: Status.Active,
  },
  {
    realName: '孙教授',
    email: 'sun@cs.edu.cn',
    phone: '13800138018',
    department: '网络工程系',
    status: Status.Active,
  },
  {
    realName: '周教授',
    email: 'zhou@cs.edu.cn',
    phone: '13800138019',
    department: '师范教育系',
    status: Status.Active,
  },
  {
    realName: '吴教授',
    email: 'wu@cs.edu.cn',
    phone: '13800138020',
    department: '师范教育系',
    status: Status.Active,
  },
];
